### ISSUE TITLE
Pacman update terminates because of dependency conflict

### ISSUE THREAD

**Issue by weiss-d** [NNBnh/superb-bootstrap#16]
I had this error until I changed Pacman update command to always answer 'yes' instead of 'default option' (see #15):
![image](https://user-images.githubusercontent.com/62437174/113475599-5dc6d000-947f-11eb-847a-2d25cde04128.png)

**Comment by NNBnh** [comment]
Hello @weiss-d, thank you so much for your dedicated on this project and sorry for my late reply/action.

I was busy studying for college and have to spend less time on coding and maintain my projects. Some of the recent feature and fix was make really rush and so the quality of the project decline.

My college study will be finished soon and after that i will definitely put more time and effort on this project.

Again, thank you so much for the bug report and pull requests, this help me a lot <3

**Comment by weiss-d** [comment]
Hi @NNBnh! I want to thank you either, because your script saved me a lot of effort while migrating to another laptop at my job. Had to spend some time to make it work for Arch-based distros though (tested on Hash and Arco Linux), so I'll make one more PR with these changes on the weekend.
