### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by codemeatloaf** [NNBnh/superb-bootstrap#2]
Whenever I run the setup command I get a syntax error;

./setup: 137: Syntax error: "}" unexpected

**Comment by NNBnh** [comment]
Thank for the report, here is some fix for you script:

https://github.com/NNBnh/superb-bootstrap/commit/1e478bc2a4d2cfc17f12fdd63aa1ca29957d5d0b#diff-8fb6d5f37e8055ce720bd0b1d56587f88c0071f285966ba17e72b2b12672aa73

**Comment by NNBnh** [comment]
Sorry @codemeatloaf for is inconvenient

Look like the fix to `line 137` has lead to another issue #3, please [follow that issue conversation](https://github.com/NNBnh/superb-bootstrap/issues/3) for more update, for now here is some quick fix you can try out:

https://github.com/NNBnh/superb-bootstrap/blob/5b8a7f2e9bd4e13f0fc5d832576adbe30b59974c/setup#L46-L49
https://github.com/NNBnh/superb-bootstrap/blob/5b8a7f2e9bd4e13f0fc5d832576adbe30b59974c/setup#L212-L248

**Comment by NNBnh** [comment]
Trully fixed !!!
