### ISSUE TITLE
Split setup in two for easier integration of usptream changes

### ISSUE THREAD

**Issue by LoricAndre** [NNBnh/superb-bootstrap#24]
When the upstream `setup` file changes, integrating those changes can be complicated if you have custom steps. It would be nice to split the file in 2 parts, one functional and one for configuration, and maybe create a helper function for `symlink_*`.

**Comment by LoricAndre** [comment]
I can work on it, but I'd like some input first. This might require putting everything in functions, having those functions in one or more files, then having a main file sourcing those and the config file and calling everything.

**Comment by NNBnh** [comment]
Hello @LoricAndre, thank you for the suggestion.
I've moved the template directory structure into its own repo [SSB template repo](https://github.com/NNBnh/superb-bootstrap-template) (later i will stick everything's together using [Git submodules](https://listed.to/@lissy93/17996/quick-tip-git-submodules))
Tomorrow I will start split the main code file into smaller pieces, improve the code quality, update the `README.md` file and write a wiki for this project...
I hope we can make this done on next week.

**Comment by NNBnh** [comment]
Done in [#5af58dc](https://github.com/NNBnh/superb-bootstrap/tree/5af58dc23a80508defeb9dbe1d6d48c53b03dff5)
