### ISSUE TITLE
./setup.sh: line 200: superbbootstrap_batch_symlink: command not found

### ISSUE THREAD

**Issue by xfzv** [NNBnh/superb-bootstrap#3]
`./setup.sh`:

```sh
Install packages

Before symlink step

Symlink to home (/home/username)
./setup.sh: line 200: superbbootstrap_batch_symlink: command not found

Symlink to root (/)
[sudo] password for username:
sudo: superbbootstrap_batch_symlink: command not found

After symlink step
```
https://github.com/NNBnh/superb-bootstrap/blob/1e478bc2a4d2cfc17f12fdd63aa1ca29957d5d0b/setup#L200

I presume there is something wrong with this block?

https://github.com/NNBnh/superb-bootstrap/blob/1e478bc2a4d2cfc17f12fdd63aa1ca29957d5d0b/setup#L126-L137

**Comment by NNBnh** [comment]
Hello, thank you for the bug report.

Here is some quick fix you can try out:

https://github.com/NNBnh/superb-bootstrap/blob/5b8a7f2e9bd4e13f0fc5d832576adbe30b59974c/setup#L46-L49
https://github.com/NNBnh/superb-bootstrap/blob/5b8a7f2e9bd4e13f0fc5d832576adbe30b59974c/setup#L212-L248

I'm very sorry for is inconvenient

**Comment by xfzv** [comment]
Thanks! it works as expected now.
