### ISSUE TITLE
[Suggestion] Clone and install paru only if it's not already installed

### ISSUE THREAD

**Issue by xfzv** [NNBnh/superb-bootstrap#4]
As I was testing the packages install feature, I noticed that this function was run although I already had [`paru`<sup>AUR</sup>](https://aur.archlinux.org/packages/paru/) installed:

https://github.com/NNBnh/superb-bootstrap/blob/1e478bc2a4d2cfc17f12fdd63aa1ca29957d5d0b/setup#L88-L94

---

https://github.com/NNBnh/superb-bootstrap/blob/1e478bc2a4d2cfc17f12fdd63aa1ca29957d5d0b/setup#L46

What about using something like this instead, so that [`paru`<sup>AUR</sup>](https://aur.archlinux.org/packages/paru/) is cloned and installed **only** if it's not already installed?

```sh
if [[ "$packagemanager_main"  = 'Pacman' ]]; then
    if ! command -v "paru" >/dev/null; then
        packagemanager_list="$packagemanager_list AUR"
    fi
        packagemanager_list="$packagemanager_list Flatpak"
fi
```

**Comment by NNBnh** [comment]
`packagemanager_list` isn't just to setup/install the package managers themself, it's also to install packages from that package manager. So we will change `superbbootstrap_AUR()` directly:

```sh
superbbootstrap_AUR() {
	if ! command -v 'paru' >/dev/null; then
		$PERMISSION_COMMAND pacman --sync --noconfirm --needed git base-devel
		git clone 'https://aur.archlinux.org/paru.git' "$TEMPORARY/paru"
		cd "$TEMPORARY/paru" || exit 1
		makepkg -si
		cd "$WD" || exit 1
	else
		printf '%s\n' "Paru has been installed"
	fi
}
```

This will be add to SBB 1.5.3

**Comment by NNBnh** [comment]
This has been add to SBB 1.5.4
