### ISSUE TITLE
Command duplicate in superbbootstrap_XBPS() function?

### ISSUE THREAD

**Issue by xfzv** [NNBnh/superb-bootstrap#6]
https://github.com/NNBnh/superb-bootstrap/blob/5b8a7f2e9bd4e13f0fc5d832576adbe30b59974c/setup#L169-L170

Not sure whether you duplicated the line by mistake or if there's a legitimate reason why the operation is run twice?

**Comment by NNBnh** [comment]
There's a legit reason to run it twice:
- The first time is to update xbps itself so it can update other packages
- The second time is to truly update packages

This should be comment beside the command in the next update

**Comment by xfzv** [comment]
My bad, I'm not very familiar with XBPS. Thanks for the explanation!
