### ISSUE TITLE
Packages not installing

### ISSUE THREAD

**Issue by obyyx** [NNBnh/superb-bootstrap#7]
Maybe I'm not doing something correctly, but this morning I migrated my dotfiles over to this and when I try to run the setup I get the output "Install packages" but nothing further, it just jumps to the symlinking. my packagesllist can be found here https://gitlab.com/obyx/dotfiles/-/blob/master/packageslist

**Comment by xfzv** [comment]
I just tried running `setup.sh` using your [packageslist](https://gitlab.com/obyx/dotfiles/-/blob/master/packageslist) layout:

```
PAC: pkg1
PAC: pkg2
[...]
```
and faced the same issue that you describe.

This works fine for me:

```
PAC:
pkg1
pkg2
[...]
```

Only specify the package manager mark once.

**Comment by obyyx** [comment]
ok, thanks so much! I guess if more than one person has had the issue it may be worth looking into clarifying the example. Nonetheless great project.

**Comment by NNBnh** [comment]
> ```
> PAC:
> pkg1
> pkg2
> [...]
> ```
> 
> Only specify the package manager mark once.

I don't even know this is possible! But i don't think this is a good practice, this might break in the future update...

> I guess if more than one person has had the issue it may be worth looking into clarifying the example.

thank you for the suggestion, this had been add to SBB 1.5.4:
```
# Mark cheat sheet:
#     APT:apt-package-name
#     PAC:pacman-package-name
#     PTG:portage-package-name
#     XBP:xbps-package-name
#     ZPR:zypper-package-name
#     AUR:aur-package-name
#     FLA:flatpak-package-name
#     HBR:homebrew-package-name
#     SNA:snap-package-name
#
# NOTE: the mark and package name must be joined by a colon in between without whitespace.
#   WRONG:
#     APT: apt-package-name
#     APT : apt-package-name
#     APT apt-package-name
#     APT:apt package name
#
#   CORRECT:
#     APT:apt-package-name
```
