### ISSUE TITLE
[Suggestion] dont install flatpack or snap unless listed in packagesList

### ISSUE THREAD

**Issue by obyyx** [NNBnh/superb-bootstrap#8]

**Comment by xfzv** [comment]
I second this. I'm using Arch Linux and I commented out the following lines because I only install packages from official Arch repositories and from the AUR.

https://github.com/NNBnh/superb-bootstrap/blob/637614e246ac3742b817cc4e9d8b66d45f10a2c9/setup#L131-L132

Maybe doing something like this?

```sh
if [[ "$PACKAGEMANAGER_MAIN"  = 'Pacman' ]; then
    PACKAGEMANAGER_LIST="$PACKAGEMANAGER_LIST AUR"
        if [[ "grep -wq 'FLA:' packageslist" ]]; then
            PACKAGEMANAGER_LIST="$PACKAGEMANAGER_LIST Flatpak"
        elif [[ "grep -wq 'SNA:' packageslist" ]]; then
            PACKAGEMANAGER_LIST="$PACKAGEMANAGER_LIST Snap"
        fi
fi

if [[ "$PACKAGEMANAGER_MAIN" != 'XBPS'   ]]; then
    if [[ "grep -wq 'SNA:' packageslist" ]]; then
            PACKAGEMANAGER_LIST="$PACKAGEMANAGER_LIST Snap"
    fi
fi
```

That's just an idea, I'm sure @NNBnh could come up with a much more elegant solution than mine.

**Comment by NNBnh** [comment]
Sorry for not document this better but this is already a feature of SBB, it loop through all the package manager that can be use on your system:

https://github.com/NNBnh/superb-bootstrap/blob/637614e246ac3742b817cc4e9d8b66d45f10a2c9/setup#L148

find all package with match mark:

https://github.com/NNBnh/superb-bootstrap/blob/637614e246ac3742b817cc4e9d8b66d45f10a2c9/setup#L152

if their is package with match mark, SBB will setup it package manager and install it's packages:

https://github.com/NNBnh/superb-bootstrap/blob/637614e246ac3742b817cc4e9d8b66d45f10a2c9/setup#L154-L162

it will also remove packages with match mark out of `packages_list` so those package don't get reinstall on another package manager later on:

https://github.com/NNBnh/superb-bootstrap/blob/637614e246ac3742b817cc4e9d8b66d45f10a2c9/setup#L155

**Comment by obyyx** [comment]
Oh ok, I didn't realize this was the case, awesome!

**Comment by NNBnh** [comment]
This feature has been documented in SBB 1.5.5
